[tool.poetry]
name = "swehockey-stat-scraper"
version = "0.1.0"
description = ""
authors = ["Robin W. <thelobst4r@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
